import { z } from 'zod'

export const BODY_TYPE_IDS = [
  'hourglass',
  'rectangle',
  'pear',
  'apple',
  'inverted-triangle',
] as const

export type BodyTypeId = (typeof BODY_TYPE_IDS)[number]

export const bodyTypeEnum = z.enum(BODY_TYPE_IDS as unknown as [BodyTypeId, ...BodyTypeId[]])

export const CelebrityRefSchema = z.object({
  name: z.string(),
  reason: z.string(),
  imageSrc: z.string(),
})

export const StyleProductSchema = z.object({
  brand: z.string(),
  name: z.string(),
  price: z.string(),
  image: z.string(),
  /** First-person styling note shown beside the product (Figma 327:440). */
  stylingNote: z.string(),
  shopUrl: z.string().optional(),
})

export type StyleProduct = z.infer<typeof StyleProductSchema>

export const BodyAnalysisSchema = z.object({
  bodyType: bodyTypeEnum,
  bodyTypeLabel: z.string(),
  silhouetteDescription: z.string(),
  whatWorksForYou: z.array(z.string()),
  whatToAvoid: z.array(z.string()),
  celebrities: z.array(CelebrityRefSchema),
  styleRecommendations: z.array(
    z.object({
      category: z.string(),
      tip: z.string(),
    })
  ),
  confidence: z.string(),
  /** Soft match percentage per body type (sums to ~100), for the UI breakdown. */
  scores: z.record(z.string(), z.number()).optional(),
  /** Editorial lead-in for the style recommendations screen (Figma 327:423). */
  styleIntro: z.string(),
  /** Curated shoppable picks for the body type. */
  styleProducts: z.array(StyleProductSchema),
  /** Present when analysis used typed measurements + Groq copy. */
  measurementAiStyling: z.string().optional(),
  analysisSource: z.enum(['photo', 'measurement']).optional(),
})

export type BodyAnalysis = z.infer<typeof BodyAnalysisSchema>
export type CelebrityRef = z.infer<typeof CelebrityRefSchema>

/** Curated styling copy + celebrity references per silhouette (not generated by AI). */
export const BODY_TYPE_PRESETS: Record<
  BodyTypeId,
  Omit<BodyAnalysis, 'bodyType' | 'confidence' | 'styleIntro' | 'styleProducts'>
> = {
  hourglass: {
    bodyTypeLabel: 'Hourglass',
    silhouetteDescription:
      'Your shoulders and hips are beautifully balanced, with a defined waist that creates natural curves. This proportional silhouette responds well to pieces that follow your shape without hiding it.',
    whatWorksForYou: [
      'Wrap tops and dresses that echo your waist',
      'High-waisted trousers and pencil skirts',
      'Belts placed at the natural waist',
      'Soft tailoring that skims rather than hides curves',
    ],
    whatToAvoid: [
      'Overly boxy layers on both top and bottom at once',
      'Low-rise cuts that break the waist line',
      'Heavy ruffles on bust and hips simultaneously',
    ],
    celebrities: [
      {
        name: 'Sofía Vergara',
        reason: 'Classic balanced curves with a defined waist',
        imageSrc: '/celebrities/sofia-vergara.webp',
      },
      {
        name: 'Beyoncé',
        reason: 'Full curves with a clear waist transition',
        imageSrc: '/celebrities/beyonce.webp',
      },
      {
        name: 'Scarlett Johansson',
        reason: 'Compact hourglass proportions on camera',
        imageSrc: '/celebrities/scarlett-johansson.webp',
      },
      {
        name: 'Marilyn Monroe',
        reason: 'Iconic hourglass reference in fashion history',
        imageSrc: '/celebrities/marilyn-monroe.webp',
      },
    ],
    styleRecommendations: [
      { category: 'Tops', tip: 'Fitted knits, wrap blouses, and V-necks keep the waist visible.' },
      { category: 'Bottoms', tip: 'High-rise straight or wide-leg pants balance hips and legs.' },
      { category: 'Dresses', tip: 'Fit-and-flare and wrap dresses are often the most flattering.' },
      { category: 'Outerwear', tip: 'Belted trenches and nipped-in blazers highlight your waist.' },
      { category: 'Accessories', tip: 'Medium-width belts and vertical lines elongate the torso.' },
    ],
  },
  rectangle: {
    bodyTypeLabel: 'Rectangle',
    silhouetteDescription:
      'Your shoulders, waist, and hips sit in a fairly straight line, giving you an athletic, streamlined look. You can add curve with cuts, belts, and strategic volume where you want emphasis.',
    whatWorksForYou: [
      'Peplum, ruffles, or draping to create waist shape',
      'A-line skirts and wide-leg trousers for subtle volume',
      'Color blocking or seams that suggest a waist',
      'Layered lightweight pieces for dimension',
    ],
    whatToAvoid: [
      'Head-to-toe boxy shapes with no waist definition',
      'Identical volume on shoulders and hips with no break',
      'Shapeless shift dresses without a belt or jacket',
    ],
    celebrities: [
      {
        name: 'Keira Knightley',
        reason: 'Straight silhouette often styled with waist emphasis',
        imageSrc: '/celebrities/keira-knightley.webp',
      },
      {
        name: 'Natalie Portman',
        reason: 'Lean rectangle lines on the red carpet',
        imageSrc: '/celebrities/natalie-portman.webp',
      },
      {
        name: 'Zendaya',
        reason: 'Long lines; stylists add shape through tailoring',
        imageSrc: '/celebrities/zendaya.webp',
      },
      {
        name: 'Cameron Diaz',
        reason: 'Athletic rectangle build in classic styling',
        imageSrc: '/celebrities/cameron-diaz.webp',
      },
    ],
    styleRecommendations: [
      { category: 'Tops', tip: 'Try wrap, knot-front, or cropped styles to shorten the torso visually.' },
      { category: 'Bottoms', tip: 'Pleats and pockets can add gentle hip volume if you want curves.' },
      { category: 'Dresses', tip: 'Bias cuts and side panels create movement without bulk.' },
      { category: 'Outerwear', tip: 'Cropped jackets and belted coats break the vertical line.' },
      { category: 'Accessories', tip: 'Statement belts and scarves draw the eye to the waist.' },
    ],
  },
  pear: {
    bodyTypeLabel: 'Pear',
    silhouetteDescription:
      'Your hips and thighs carry more volume than your shoulders, with a comparatively smaller upper body. Balance and elongating the shoulder line often flatter this shape beautifully.',
    whatWorksForYou: [
      'Boat necks, off-shoulder, and structured shoulders',
      'Dark or simple bottoms with detailed tops',
      'A-line skirts that glide over hips',
      'Straight or wide-leg pants in fluid fabrics',
    ],
    whatToAvoid: [
      'Tight pencil skirts with very narrow shoulders',
      'Heavy details or pockets only on the hips',
      'Super-cropped jackets that end at the widest hip point',
    ],
    celebrities: [
      {
        name: 'Jennifer Lopez',
        reason: 'Curvier lower body with strong styling balance',
        imageSrc: '/celebrities/jennifer-lopez.webp',
      },
      {
        name: 'Shakira',
        reason: 'Hip-forward silhouette often balanced on stage',
        imageSrc: '/celebrities/shakira.webp',
      },
      {
        name: 'America Ferrera',
        reason: 'Pear-leaning proportions in tailored looks',
        imageSrc: '/celebrities/america-ferrera.webp',
      },
      {
        name: 'Rihanna',
        reason: 'Often styled to balance shoulders and hips',
        imageSrc: '/celebrities/rihanna.webp',
      },
    ],
    styleRecommendations: [
      { category: 'Tops', tip: 'Bright colors, shoulder detail, and collars draw the eye upward.' },
      { category: 'Bottoms', tip: 'Mid- or high-rise dark denim streamlines the lower body.' },
      { category: 'Dresses', tip: 'Empire and fit-and-flare lines skim without clinging.' },
      { category: 'Outerwear', tip: 'Hip-length jackets with structured shoulders harmonize proportions.' },
      { category: 'Accessories', tip: 'Statement earrings and necklaces keep focus near the face.' },
    ],
  },
  apple: {
    bodyTypeLabel: 'Apple',
    silhouetteDescription:
      'You carry more fullness through the midsection, often with great legs and a full bust. Flowing lines that skim the torso and open necklines usually feel comfortable and polished.',
    whatWorksForYou: [
      'Empire waists and tunics that float over the midsection',
      'V-necks and vertical seams that elongate',
      'Structured shoulders with a relaxed torso',
      'Straight or bootcut pants to balance the frame',
    ],
    whatToAvoid: [
      'Very tight clingy knits around the midsection',
      'Wide belts sitting exactly at the fullest point',
      'Double-breasted bulk with no vertical break',
    ],
    celebrities: [
      {
        name: 'Drew Barrymore',
        reason: 'Soft midsection often styled with flowing lines',
        imageSrc: '/celebrities/drew-barrymore.webp',
      },
      {
        name: 'Melissa McCarthy',
        reason: 'Great example of apple-friendly tailoring on screen',
        imageSrc: '/celebrities/melissa-mccarthy.webp',
      },
      {
        name: 'Queen Latifah',
        reason: 'Strong vertical styling and empire silhouettes',
        imageSrc: '/celebrities/queen-latifah.webp',
      },
      {
        name: 'Oprah Winfrey',
        reason: 'Classic apple proportions in polished tailoring',
        imageSrc: '/celebrities/oprah-winfrey.webp',
      },
    ],
    styleRecommendations: [
      { category: 'Tops', tip: 'Wrap and surplice tops create a flattering diagonal line.' },
      { category: 'Bottoms', tip: 'Straight-leg trousers balance a softer torso line.' },
      { category: 'Dresses', tip: 'Shift and trapeze dresses skim without pulling across the waist.' },
      { category: 'Outerwear', tip: 'Open-front longline cardigans add length without cling.' },
      { category: 'Accessories', tip: 'Long pendant necklaces add a vertical focal point.' },
    ],
  },
  'inverted-triangle': {
    bodyTypeLabel: 'Inverted Triangle',
    silhouetteDescription:
      'Your shoulders and upper body are broader than your hips, giving a strong, athletic presence. The goal is often to soften the shoulder line and add gentle volume below the waist.',
    whatWorksForYou: [
      'Full or A-line skirts and wide-leg pants',
      'Simple necklines without extra shoulder padding',
      'Hip pockets, pleats, or lighter colors on the lower half',
      'Fluid fabrics on top with more structure below',
    ],
    whatToAvoid: [
      'Strong shoulder pads with very narrow bottoms',
      'Halters that emphasize shoulder width alone',
      'Skinny jeans with very bulky upper layers',
    ],
    celebrities: [
      {
        name: 'Angelina Jolie',
        reason: 'Broad shoulders often balanced with soft skirts',
        imageSrc: '/celebrities/angelina-jolie.webp',
      },
      {
        name: 'Naomi Campbell',
        reason: 'Runway shoulders with stylists adding hip volume',
        imageSrc: '/celebrities/naomi-campbell.webp',
      },
      {
        name: 'Demi Moore',
        reason: 'Athletic inverted triangle in tailored looks',
        imageSrc: '/celebrities/demi-moore.webp',
      },
      {
        name: 'Renée Zellweger',
        reason: 'Broader upper frame styled with A-line shapes',
        imageSrc: '/celebrities/renee-zellweger.webp',
      },
    ],
    styleRecommendations: [
      { category: 'Tops', tip: 'Scoop and U-necks soften the shoulder line.' },
      { category: 'Bottoms', tip: 'Flared and bootcut jeans add proportion below the hip.' },
      { category: 'Dresses', tip: 'Hem interest and skirts with movement balance shoulders.' },
      { category: 'Outerwear', tip: 'Waterfall and unlined trenches avoid extra bulk on top.' },
      { category: 'Accessories', tip: 'Belts at the hip draw attention to the lower body.' },
    ],
  },
}

/**
 * Curated editorial intro + shoppable picks per silhouette (Figma 327:423).
 * Kept separate from BODY_TYPE_PRESETS so styling copy and catalog evolve
 * independently. Every product uses a locally optimized image sourced from
 * its retailer page; price labels remain live-link based to avoid stale copy.
 */
export const STYLE_EDITORIAL: Record<BodyTypeId, { intro: string; products: StyleProduct[] }> = {
  hourglass: {
    intro:
      'Your superpower is balance — so the goal is to honor the waist, never bury it. These are the pieces that follow your curves instead of fighting them, from waist-defining knits to high-rise denim that lets your proportions do the talking.',
    products: [
      { brand: 'Zara', name: 'Z1975 High-Rise Straight Jeans', price: 'View current price', image: '/products/zara-z1975-hi-rise-straight-jeans.webp', stylingNote: 'A clean high rise keeps the waist as the focal point.', shopUrl: 'https://www.zara.com/us/en/z1975-hi-rise-straight-jeans-p01934041.html' },
      { brand: 'Abercrombie & Fitch', name: 'A&F Sloane Tailored Wide-Leg Pant', price: 'View current price', image: '/products/abercrombie-sloane-wide-leg-pant.webp', stylingNote: 'A structured waist and wider leg preserve your natural balance.', shopUrl: 'https://www.abercrombie.com/shop/us/p/tailored-wide-leg-pants-51625331' },
      { brand: 'H&M', name: 'Wrap Dress', price: 'View current price', image: '/products/hm-wrap-dress.webp', stylingNote: 'The wrap construction follows the waist without hiding it.', shopUrl: 'https://www2.hm.com/en_us/productpage.1285149003.html' },
      { brand: 'Zara Pre-Owned', name: 'Belted Wool Blazer', price: 'View current price', image: '/products/zara-belted-wool-blazer.webp', stylingNote: 'The belt creates definition while the soft tailoring follows your curves.', shopUrl: 'https://www.zara.com/us/en/preowned-resell/product-detail/1713554' },
      { brand: 'Zara', name: 'Striped Pleated Balloon Pants', price: 'View current price', image: '/products/zara-striped-pleated-balloon-pants.webp', stylingNote: 'A fitted waist and full leg keep the top-to-bottom balance intact.', shopUrl: 'https://www.zara.com/us/en/striped-pleated-balloon-pants-p01255527.html' },
    ],
  },
  rectangle: {
    intro:
      "Straight, clean lines are a blank canvas — you get to build curve wherever you want it. These picks add shape through cut, volume and belting, so you can create a waist on demand and play with proportion all season.",
    products: [
      { brand: 'H&M', name: 'Relaxed Button-Down Shirt', price: 'View current price', image: '/products/hm-relaxed-button-down-shirt.webp', stylingNote: 'The relaxed line adds dimension while the buttons lead the eye vertically.', shopUrl: 'https://www2.hm.com/en_us/productpage.1344514001.html' },
      { brand: 'Zara', name: 'Striped Pleated Balloon Pants', price: 'View current price', image: '/products/zara-striped-pleated-balloon-pants.webp', stylingNote: 'Pleats add gentle hip volume and a clear waist break.', shopUrl: 'https://www.zara.com/us/en/striped-pleated-balloon-pants-p01255527.html' },
      { brand: 'Abercrombie & Fitch', name: 'A&F Sloane Tailored Wide-Leg Pant', price: 'View current price', image: '/products/abercrombie-sloane-wide-leg-pant.webp', stylingNote: 'A tailored waistband creates shape while the leg adds movement.', shopUrl: 'https://www.abercrombie.com/shop/us/p/tailored-wide-leg-pants-51625331' },
      { brand: 'Zara', name: 'ZW Collection Curved Straight Jeans', price: 'View current price', image: '/products/zara-curved-straight-jeans.webp', stylingNote: 'The curved cut builds dimension through the hip and leg.', shopUrl: 'https://www.zara.com/us/en/zw-collection-curved-straight-mid-rise-jeans-p09632273.html' },
      { brand: 'Zara Pre-Owned', name: 'Belted Wool Blazer', price: 'View current price', image: '/products/zara-belted-wool-blazer.webp', stylingNote: 'The belt adds instant structure and creates waist definition.', shopUrl: 'https://www.zara.com/us/en/preowned-resell/product-detail/1713554' },
    ],
  },
  pear: {
    intro:
      'The play here is balance — draw the eye up and let the lower half stay simple and fluid. Think detailed, brighter tops, structured shoulders, and bottoms that skim rather than cling.',
    products: [
      { brand: 'H&M', name: 'Relaxed Button-Down Shirt', price: 'View current price', image: '/products/hm-relaxed-button-down-shirt.webp', stylingNote: 'The crisp collar and lighter color draw attention upward.', shopUrl: 'https://www2.hm.com/en_us/productpage.1344514001.html' },
      { brand: 'Zara', name: 'Z1975 High-Rise Straight Jeans', price: 'View current price', image: '/products/zara-z1975-hi-rise-straight-jeans.webp', stylingNote: 'A clean straight leg skims the lower half without clinging.', shopUrl: 'https://www.zara.com/us/en/z1975-hi-rise-straight-jeans-p01934041.html' },
      { brand: 'Zara', name: 'Striped Pleated Balloon Pants', price: 'View current price', image: '/products/zara-striped-pleated-balloon-pants.webp', stylingNote: 'Fluid volume falls from a defined waist and moves away from the hip.', shopUrl: 'https://www.zara.com/us/en/striped-pleated-balloon-pants-p01255527.html' },
      { brand: 'Abercrombie & Fitch', name: 'A&F Sloane Tailored Wide-Leg Pant', price: 'View current price', image: '/products/abercrombie-sloane-wide-leg-pant.webp', stylingNote: 'A full-length tailored leg creates one long, balanced line.', shopUrl: 'https://www.abercrombie.com/shop/us/p/tailored-wide-leg-pants-51625331' },
      { brand: 'H&M', name: 'Wrap Dress', price: 'View current price', image: '/products/hm-wrap-dress.webp', stylingNote: 'The wrap defines the waist and the skirt releases cleanly over the hips.', shopUrl: 'https://www2.hm.com/en_us/productpage.1285149003.html' },
    ],
  },
  apple: {
    intro:
      'Flowing, vertical lines are your best friend — pieces that skim the midsection and open up the neckline feel effortless. These picks elongate and float instead of cling.',
    products: [
      { brand: 'H&M', name: 'Wrap Dress', price: 'View current price', image: '/products/hm-wrap-dress.webp', stylingNote: 'A V neckline and diagonal wrap create a long, open line.', shopUrl: 'https://www2.hm.com/en_us/productpage.1285149003.html' },
      { brand: 'H&M', name: 'Relaxed Button-Down Shirt', price: 'View current price', image: '/products/hm-relaxed-button-down-shirt.webp', stylingNote: 'Wear it slightly open for an easy vertical break through the torso.', shopUrl: 'https://www2.hm.com/en_us/productpage.1344514001.html' },
      { brand: 'Abercrombie & Fitch', name: 'A&F Sloane Tailored Wide-Leg Pant', price: 'View current price', image: '/products/abercrombie-sloane-wide-leg-pant.webp', stylingNote: 'The clean leg balances the torso with structure below.', shopUrl: 'https://www.abercrombie.com/shop/us/p/tailored-wide-leg-pants-51625331' },
      { brand: 'Zara', name: 'ZW Collection Curved Straight Jeans', price: 'View current price', image: '/products/zara-curved-straight-jeans.webp', stylingNote: 'A straighter leg keeps the silhouette clean and uninterrupted.', shopUrl: 'https://www.zara.com/us/en/zw-collection-curved-straight-mid-rise-jeans-p09632273.html' },
      { brand: 'Zara Pre-Owned', name: 'Belted Wool Blazer', price: 'View current price', image: '/products/zara-belted-wool-blazer.webp', stylingNote: 'Wear it open for vertical length or softly tied for definition.', shopUrl: 'https://www.zara.com/us/en/preowned-resell/product-detail/1713554' },
    ],
  },
  'inverted-triangle': {
    intro:
      'The goal is to soften the shoulder line and add gentle volume below the waist. These picks bring fluidity up top and structure or movement on the bottom to even out a strong upper frame.',
    products: [
      { brand: 'H&M', name: 'Relaxed Button-Down Shirt', price: 'View current price', image: '/products/hm-relaxed-button-down-shirt.webp', stylingNote: 'A fluid shoulder and open neckline soften the upper frame.', shopUrl: 'https://www2.hm.com/en_us/productpage.1344514001.html' },
      { brand: 'Abercrombie & Fitch', name: 'A&F Sloane Tailored Wide-Leg Pant', price: 'View current price', image: '/products/abercrombie-sloane-wide-leg-pant.webp', stylingNote: 'The wide leg adds proportion below the hip.', shopUrl: 'https://www.abercrombie.com/shop/us/p/tailored-wide-leg-pants-51625331' },
      { brand: 'Zara', name: 'Striped Pleated Balloon Pants', price: 'View current price', image: '/products/zara-striped-pleated-balloon-pants.webp', stylingNote: 'Pleats and a balloon line bring movement to the lower half.', shopUrl: 'https://www.zara.com/us/en/striped-pleated-balloon-pants-p01255527.html' },
      { brand: 'Zara', name: 'ZW Collection Curved Straight Jeans', price: 'View current price', image: '/products/zara-curved-straight-jeans.webp', stylingNote: 'The curved cut builds a little more dimension through the hip.', shopUrl: 'https://www.zara.com/us/en/zw-collection-curved-straight-mid-rise-jeans-p09632273.html' },
      { brand: 'H&M', name: 'Wrap Dress', price: 'View current price', image: '/products/hm-wrap-dress.webp', stylingNote: 'A softer top and fuller skirt redirect the eye below the shoulder.', shopUrl: 'https://www2.hm.com/en_us/productpage.1285149003.html' },
    ],
  },
}

export function buildAnalysisFromBodyType(bodyType: BodyTypeId, confidence: string): BodyAnalysis {
  const preset = BODY_TYPE_PRESETS[bodyType]
  const editorial = STYLE_EDITORIAL[bodyType]
  return {
    bodyType,
    confidence,
    ...preset,
    styleIntro: editorial.intro,
    styleProducts: editorial.products,
  }
}

/** What Groq is allowed to return (classification only). */
const normalizeBodyTypeSlug = (v: unknown) =>
  typeof v === 'string' ? v.toLowerCase().trim().replace(/_/g, '-') : v

export const AiBodyClassificationSchema = z.object({
  bodyType: bodyTypeEnum.catch('rectangle'),
  confidence: z.enum(['high', 'medium', 'low']).catch('medium'),
})

export type AiBodyClassification = z.infer<typeof AiBodyClassificationSchema>

/** Strict parse for Groq JSON responses (invalid → parse error, no silent defaults). */
export const AiBodyClassificationGroqSchema = z.object({
  bodyType: z.preprocess(normalizeBodyTypeSlug, bodyTypeEnum.catch('rectangle')),
  confidence: z.preprocess((v) => (typeof v === 'string' ? v.toLowerCase().trim() : v), z.enum(['high', 'medium', 'low'])),
})
