import { z } from 'zod'

export const BODY_TYPE_IDS = [
  'hourglass',
  'rectangle',
  'pear',
  'apple',
  'inverted-triangle',
] as const

export type BodyTypeId = (typeof BODY_TYPE_IDS)[number]

const bodyTypeEnum = z.enum(BODY_TYPE_IDS as unknown as [BodyTypeId, ...BodyTypeId[]])

export const CelebrityRefSchema = z.object({
  name: z.string(),
  reason: z.string(),
  imageSrc: z.string(),
})

export const BodyAnalysisSchema = z.object({
  bodyType: bodyTypeEnum,
  bodyTypeLabel: z.string(),
  silhouetteDescription: z.string(),
  whatWorksForYou: z.array(z.string()),
  whatToAvoid: z.array(z.string()),
  celebrities: z.array(CelebrityRefSchema),
  styleRecommendations: z.array(
    z.object({
      category: z.string(),
      tip: z.string(),
    })
  ),
  confidence: z.string(),
})

export type BodyAnalysis = z.infer<typeof BodyAnalysisSchema>
export type CelebrityRef = z.infer<typeof CelebrityRefSchema>

/** Curated styling copy + celebrity references per silhouette (not generated by AI). */
export const BODY_TYPE_PRESETS: Record<BodyTypeId, Omit<BodyAnalysis, 'bodyType' | 'confidence'>> = {
  hourglass: {
    bodyTypeLabel: 'Hourglass',
    silhouetteDescription:
      'Your shoulders and hips are beautifully balanced, with a defined waist that creates natural curves. This proportional silhouette responds well to pieces that follow your shape without hiding it.',
    whatWorksForYou: [
      'Wrap tops and dresses that echo your waist',
      'High-waisted trousers and pencil skirts',
      'Belts placed at the natural waist',
      'Soft tailoring that skims rather than hides curves',
    ],
    whatToAvoid: [
      'Overly boxy layers on both top and bottom at once',
      'Low-rise cuts that break the waist line',
      'Heavy ruffles on bust and hips simultaneously',
    ],
    celebrities: [
      {
        name: 'Sofía Vergara',
        reason: 'Classic balanced curves with a defined waist',
        imageSrc: '/celebrities/celebrity-1.jpg',
      },
      {
        name: 'Beyoncé',
        reason: 'Full curves with a clear waist transition',
        imageSrc: '/celebrities/celebrity-2.jpg',
      },
      {
        name: 'Scarlett Johansson',
        reason: 'Compact hourglass proportions on camera',
        imageSrc: '/celebrities/celebrity-3.jpg',
      },
      {
        name: 'Marilyn Monroe',
        reason: 'Iconic hourglass reference in fashion history',
        imageSrc: '/celebrities/celebrity-4.jpg',
      },
    ],
    styleRecommendations: [
      { category: 'Tops', tip: 'Fitted knits, wrap blouses, and V-necks keep the waist visible.' },
      { category: 'Bottoms', tip: 'High-rise straight or wide-leg pants balance hips and legs.' },
      { category: 'Dresses', tip: 'Fit-and-flare and wrap dresses are often the most flattering.' },
      { category: 'Outerwear', tip: 'Belted trenches and nipped-in blazers highlight your waist.' },
      { category: 'Accessories', tip: 'Medium-width belts and vertical lines elongate the torso.' },
    ],
  },
  rectangle: {
    bodyTypeLabel: 'Rectangle',
    silhouetteDescription:
      'Your shoulders, waist, and hips sit in a fairly straight line, giving you an athletic, streamlined look. You can add curve with cuts, belts, and strategic volume where you want emphasis.',
    whatWorksForYou: [
      'Peplum, ruffles, or draping to create waist shape',
      'A-line skirts and wide-leg trousers for subtle volume',
      'Color blocking or seams that suggest a waist',
      'Layered lightweight pieces for dimension',
    ],
    whatToAvoid: [
      'Head-to-toe boxy shapes with no waist definition',
      'Identical volume on shoulders and hips with no break',
      'Shapeless shift dresses without a belt or jacket',
    ],
    celebrities: [
      {
        name: 'Keira Knightley',
        reason: 'Straight silhouette often styled with waist emphasis',
        imageSrc: '/celebrities/celebrity-1.jpg',
      },
      {
        name: 'Natalie Portman',
        reason: 'Lean rectangle lines on the red carpet',
        imageSrc: '/celebrities/celebrity-2.jpg',
      },
      {
        name: 'Zendaya',
        reason: 'Long lines; stylists add shape through tailoring',
        imageSrc: '/celebrities/celebrity-3.jpg',
      },
      {
        name: 'Cameron Diaz',
        reason: 'Athletic rectangle build in classic styling',
        imageSrc: '/celebrities/celebrity-4.jpg',
      },
    ],
    styleRecommendations: [
      { category: 'Tops', tip: 'Try wrap, knot-front, or cropped styles to shorten the torso visually.' },
      { category: 'Bottoms', tip: 'Pleats and pockets can add gentle hip volume if you want curves.' },
      { category: 'Dresses', tip: 'Bias cuts and side panels create movement without bulk.' },
      { category: 'Outerwear', tip: 'Cropped jackets and belted coats break the vertical line.' },
      { category: 'Accessories', tip: 'Statement belts and scarves draw the eye to the waist.' },
    ],
  },
  pear: {
    bodyTypeLabel: 'Pear',
    silhouetteDescription:
      'Your hips and thighs carry more volume than your shoulders, with a comparatively smaller upper body. Balance and elongating the shoulder line often flatter this shape beautifully.',
    whatWorksForYou: [
      'Boat necks, off-shoulder, and structured shoulders',
      'Dark or simple bottoms with detailed tops',
      'A-line skirts that glide over hips',
      'Straight or wide-leg pants in fluid fabrics',
    ],
    whatToAvoid: [
      'Tight pencil skirts with very narrow shoulders',
      'Heavy details or pockets only on the hips',
      'Super-cropped jackets that end at the widest hip point',
    ],
    celebrities: [
      {
        name: 'Jennifer Lopez',
        reason: 'Curvier lower body with strong styling balance',
        imageSrc: '/celebrities/celebrity-1.jpg',
      },
      {
        name: 'Shakira',
        reason: 'Hip-forward silhouette often balanced on stage',
        imageSrc: '/celebrities/celebrity-2.jpg',
      },
      {
        name: 'America Ferrera',
        reason: 'Pear-leaning proportions in tailored looks',
        imageSrc: '/celebrities/celebrity-3.jpg',
      },
      {
        name: 'Rihanna',
        reason: 'Often styled to balance shoulders and hips',
        imageSrc: '/celebrities/celebrity-4.jpg',
      },
    ],
    styleRecommendations: [
      { category: 'Tops', tip: 'Bright colors, shoulder detail, and collars draw the eye upward.' },
      { category: 'Bottoms', tip: 'Mid- or high-rise dark denim streamlines the lower body.' },
      { category: 'Dresses', tip: 'Empire and fit-and-flare lines skim without clinging.' },
      { category: 'Outerwear', tip: 'Hip-length jackets with structured shoulders harmonize proportions.' },
      { category: 'Accessories', tip: 'Statement earrings and necklaces keep focus near the face.' },
    ],
  },
  apple: {
    bodyTypeLabel: 'Apple',
    silhouetteDescription:
      'You carry more fullness through the midsection, often with great legs and a full bust. Flowing lines that skim the torso and open necklines usually feel comfortable and polished.',
    whatWorksForYou: [
      'Empire waists and tunics that float over the midsection',
      'V-necks and vertical seams that elongate',
      'Structured shoulders with a relaxed torso',
      'Straight or bootcut pants to balance the frame',
    ],
    whatToAvoid: [
      'Very tight clingy knits around the midsection',
      'Wide belts sitting exactly at the fullest point',
      'Double-breasted bulk with no vertical break',
    ],
    celebrities: [
      {
        name: 'Drew Barrymore',
        reason: 'Soft midsection often styled with flowing lines',
        imageSrc: '/celebrities/celebrity-1.jpg',
      },
      {
        name: 'Melissa McCarthy',
        reason: 'Great example of apple-friendly tailoring on screen',
        imageSrc: '/celebrities/celebrity-2.jpg',
      },
      {
        name: 'Queen Latifah',
        reason: 'Strong vertical styling and empire silhouettes',
        imageSrc: '/celebrities/celebrity-3.jpg',
      },
      {
        name: 'Oprah Winfrey',
        reason: 'Classic apple proportions in polished tailoring',
        imageSrc: '/celebrities/celebrity-4.jpg',
      },
    ],
    styleRecommendations: [
      { category: 'Tops', tip: 'Wrap and surplice tops create a flattering diagonal line.' },
      { category: 'Bottoms', tip: 'Straight-leg trousers balance a softer torso line.' },
      { category: 'Dresses', tip: 'Shift and trapeze dresses skim without pulling across the waist.' },
      { category: 'Outerwear', tip: 'Open-front longline cardigans add length without cling.' },
      { category: 'Accessories', tip: 'Long pendant necklaces add a vertical focal point.' },
    ],
  },
  'inverted-triangle': {
    bodyTypeLabel: 'Inverted Triangle',
    silhouetteDescription:
      'Your shoulders and upper body are broader than your hips, giving a strong, athletic presence. The goal is often to soften the shoulder line and add gentle volume below the waist.',
    whatWorksForYou: [
      'Full or A-line skirts and wide-leg pants',
      'Simple necklines without extra shoulder padding',
      'Hip pockets, pleats, or lighter colors on the lower half',
      'Fluid fabrics on top with more structure below',
    ],
    whatToAvoid: [
      'Strong shoulder pads with very narrow bottoms',
      'Halters that emphasize shoulder width alone',
      'Skinny jeans with very bulky upper layers',
    ],
    celebrities: [
      {
        name: 'Angelina Jolie',
        reason: 'Broad shoulders often balanced with soft skirts',
        imageSrc: '/celebrities/celebrity-1.jpg',
      },
      {
        name: 'Naomi Campbell',
        reason: 'Runway shoulders with stylists adding hip volume',
        imageSrc: '/celebrities/celebrity-2.jpg',
      },
      {
        name: 'Demi Moore',
        reason: 'Athletic inverted triangle in tailored looks',
        imageSrc: '/celebrities/celebrity-3.jpg',
      },
      {
        name: 'Renée Zellweger',
        reason: 'Broader upper frame styled with A-line shapes',
        imageSrc: '/celebrities/celebrity-4.jpg',
      },
    ],
    styleRecommendations: [
      { category: 'Tops', tip: 'Scoop and U-necks soften the shoulder line.' },
      { category: 'Bottoms', tip: 'Flared and bootcut jeans add proportion below the hip.' },
      { category: 'Dresses', tip: 'Hem interest and skirts with movement balance shoulders.' },
      { category: 'Outerwear', tip: 'Waterfall and unlined trenches avoid extra bulk on top.' },
      { category: 'Accessories', tip: 'Belts at the hip draw attention to the lower body.' },
    ],
  },
}

export function buildAnalysisFromBodyType(bodyType: BodyTypeId, confidence: string): BodyAnalysis {
  const preset = BODY_TYPE_PRESETS[bodyType]
  return {
    bodyType,
    confidence,
    ...preset,
  }
}

/** What Groq is allowed to return (classification only). */
export const AiBodyClassificationSchema = z.object({
  bodyType: bodyTypeEnum.catch('rectangle'),
  confidence: z.enum(['high', 'medium', 'low']).catch('medium'),
})

export type AiBodyClassification = z.infer<typeof AiBodyClassificationSchema>
